name: deploy

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.20

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Test
        run: go test -v -race ./...
  deploy:
    name: deploy
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # id-token: write
    env:
      # You need to modify these values
      PROJECT_ID: seccamp2023-b4-rung
      RUN_SA_ID: run-helloworld@seccamp2023-b4-rung.iam.gserviceaccount.com
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup ko
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - name: supplychain attacks (Exercise 2)
        uses: ./supplychain
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
          # provider info: https://console.cloud.google.com/iam-admin/workload-identity-pools/pool/training-pool/provider/training-provider
          # workload_identity_provider: 'projects/<Project Number>/locations/global/workloadIdentityPools/training-pool/providers/training-provider'
          # service_account: 'app-actions-cd@<Project ID>.iam.gserviceaccount.com'
      - name: 'Build and Push a container image to Artifact Registry'
        run: |-
          # Artifact Registry (Google's container registry) is configured via Terraform
          gcloud auth configure-docker us-docker.pkg.dev --quiet
      - uses: ko-build/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: us-docker.pkg.dev/${{ env.PROJECT_ID }}/training-helloworld/helloworld
      - run: |-
          ko build --bare --tags ${{ github.sha }},latest
      - name: 'Deploy to Cloud Run'
        run: |-
          gcloud run deploy training-helloworld \
            --region us-central1 \
            --image "us-docker.pkg.dev/${{ env.PROJECT_ID }}/training-helloworld/helloworld:${{ github.sha }}" \
            --service-account ${{ env.RUN_SA_ID }} \
            --platform managed \
            --allow-unauthenticated
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.1
      - name: Write SBOM to stdout to see the data
        run: cosign download sbom us-docker.pkg.dev/${{ env.PROJECT_ID }}/training-helloworld/helloworld:${{ github.sha }}
